from typing import Dict, List
from app.models.schemas import DownloadConfig, PresetDefinition, PresetsResponse

CANONICAL_PRESETS: Dict[str, PresetDefinition] = {
    "recommended": PresetDefinition(
        id="recommended",
        name="Recommended",
        description="Balanced standard for maximum compatibility. Best video and audio merged into MP4 with metadata.",
        badge="Default",
        config=DownloadConfig(
            preset="recommended",
            quality="best",
            output_container="mp4",
            audio_mode="merge",
            audio_format="mp3",
            audio_quality="0",
            video_codec="any",
            filename_template="%(title).150B.%(ext)s",
            subtitles=False,
            embed_subtitles=False,
            embed_metadata=True,
            embed_thumbnail=True,
            write_chapters=False,
            retries=10,
            timeout=30,
            concurrent_fragments=1,
            playlist_mode="single",
        ),
    ),
    "best_quality": PresetDefinition(
        id="best_quality",
        name="Best Quality",
        description="Highest possible visual & audio fidelity (up to 4K/8K) preserved in MKV with chapters and metadata.",
        badge="Pro",
        config=DownloadConfig(
            preset="best_quality",
            quality="best",
            output_container="mkv",
            audio_mode="merge",
            audio_format="mp3",
            audio_quality="0",
            video_codec="any",
            filename_template="%(title).150B.%(ext)s",
            subtitles=False,
            embed_subtitles=False,
            embed_metadata=True,
            embed_thumbnail=True,
            write_chapters=True,
            retries=15,
            timeout=45,
            concurrent_fragments=2,
            playlist_mode="single",
        ),
    ),
    "audio_only": PresetDefinition(
        id="audio_only",
        name="Audio Only",
        description="Extracts pure audio stream and transcodes to pristine 320 kbps MP3 with album artwork embedded.",
        badge="Music",
        config=DownloadConfig(
            preset="audio_only",
            quality="best",
            output_container="mp3",
            audio_mode="audio_only",
            audio_format="mp3",
            audio_quality="0",
            video_codec="any",
            filename_template="%(title).150B.%(ext)s",
            subtitles=False,
            embed_subtitles=False,
            embed_metadata=True,
            embed_thumbnail=True,
            write_chapters=False,
            retries=10,
            timeout=30,
            concurrent_fragments=1,
            playlist_mode="single",
        ),
    ),
    "small_file": PresetDefinition(
        id="small_file",
        name="Small File",
        description="Efficient 720p H.264 profile optimized for lightweight sharing, tablets, and mobile devices.",
        badge="Compact",
        config=DownloadConfig(
            preset="small_file",
            quality="720p",
            output_container="mp4",
            audio_mode="merge",
            audio_format="mp3",
            audio_quality="2",
            video_codec="h264",
            filename_template="%(title).150B.%(ext)s",
            subtitles=False,
            embed_subtitles=False,
            embed_metadata=False,
            embed_thumbnail=False,
            write_chapters=False,
            retries=5,
            timeout=25,
            concurrent_fragments=1,
            playlist_mode="single",
        ),
    ),
    "archive": PresetDefinition(
        id="archive",
        name="Archive",
        description="Long-term preservation profile: uncompressed streams, subtitles, chapters, and all embedded tags.",
        badge="Preservation",
        config=DownloadConfig(
            preset="archive",
            quality="best",
            output_container="mkv",
            audio_mode="merge",
            audio_format="mp3",
            audio_quality="0",
            video_codec="any",
            filename_template="%(title).150B.%(ext)s",
            subtitles=True,
            embed_subtitles=True,
            subtitle_langs="en,all",
            embed_metadata=True,
            embed_thumbnail=True,
            write_chapters=True,
            retries=20,
            timeout=60,
            concurrent_fragments=2,
            playlist_mode="single",
        ),
    ),
}


class PresetService:
    @staticmethod
    def get_all_presets() -> PresetsResponse:
        return PresetsResponse(
            presets=list(CANONICAL_PRESETS.values()),
            default_preset="recommended",
        )

    @staticmethod
    def get_preset(preset_id: str) -> PresetDefinition:
        return CANONICAL_PRESETS.get(preset_id.lower(), CANONICAL_PRESETS["recommended"])
